
#    __   __     __    ___  ____  __  ____  ____  _  _     ___  __   __ _  ____  __  ___ 
#   / _\ (  )   / _\  / __)(  _ \(  )(_  _)(_  _)( \/ )   / __)/  \ (  ( \(  __)(  )/ __)
#  /    \/ (_/\/    \( (__  )   / )(   )(    )(   )  /   ( (__(  O )/    / ) _)  )(( (_ \
#  \_/\_/\____/\_/\_/ \___)(__\_)(__) (__)  (__) (__/     \___)\__/ \_)__)(__)  (__)\___/
#

font:
 normal:
  family: monospace
 bold:
  family: monospace
 italic:
  family: monospace
 size: 14

window:
 padding:
  x: 32
  y: 32

background_opacity: 0.8

